name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 159.223.72.233 > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Debug SSH Connection
      run: |
        ssh -vvv dokku@159.223.72.233 exit

    - name: Deploy to Dokku
      run: |
        git remote add dokku dokku@159.223.72.233:todo-list-app
        git push dokku main
