name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Dokku
      run: |
        ssh-keyscan -H <YOUR_DROPLET_IP> >> ~/.ssh/known_hosts
        git remote add dokku dokku@<YOUR_DROPLET_IP>:todo-list-app
        git push dokku main
      env:
        DOKKU_SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
