name: Deploy to Dokku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Dokku
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
          DOKKU_APP: your_app_name
          DOKKU_KEY: ${{ secrets.DOKKU_KEY }}
        run: |
          echo "$DOKKU_KEY" > dokku_key
          chmod 600 dokku_key
          ssh -i dokku_key -o StrictHostKeyChecking=no dokku@$DOKKU_HOST git:from-archive master
