name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Dokku
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
          DOKKU_KEY: ${{ secrets.DOKKU_KEY }}
        run: |
          echo "${{ secrets.DOKKU_KEY }}" > dokku_key
          chmod 600 dokku_key
          ssh -o StrictHostKeyChecking=no -i dokku_key dokku@$DOKKU_HOST git:from-archive master
