name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        touch ~/.ssh/known_hosts
        ssh-keyscan -H 157.245.60.124 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no dokku@157.245.60.124 exit

    - name: Deploy to Dokku
      run: |
        git remote add dokku dokku@157.245.60.124:todo-list-app
        git push dokku main
