name: CI/CD Pipeline for Todo List App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  # Use your GitHub Personal Access Token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t todo-list-app .

      - name: Log in to Dokku
        run: |
          echo "${{ secrets.DOKKU_PRIVATE_KEY }}" > dokku_key
          chmod 600 dokku_key
          ssh -o StrictHostKeyChecking=no -i dokku_key dokku@157.245.60.124 "dokku apps:create todo-list-app || echo 'App already exists.'"

      - name: Push Docker image to Dokku
        run: |
          docker tag todo-list-app dokku@157.245.60.124:todo-list-app
          docker push dokku@157.245.60.124:todo-list-app

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Deploy to Dokku
        run: |
          echo "${{ secrets.DOKKU_PRIVATE_KEY }}" > dokku_key
          chmod 600 dokku_key
          ssh -o StrictHostKeyChecking=no -i dokku_key dokku@157.245.60.124 ps:restart todo-list-app

      - name: Notify deployment
        run: |
          echo "Deployment to Dokku completed successfully!"
