name: Deploy Todo List App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Explicitly set the runner version

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure a full clone

      # Step 2: Create .ssh directory and add Dokku server SSH key to known_hosts
      - name: Create .ssh directory and add Dokku server SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 139.59.123.238 >> ~/.ssh/known_hosts

      # Step 3: Set up the SSH agent and load the SSH private key
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MY_SSH_KEY }}

      # Step 4: Add Dokku remote if not already added
      - name: Add Dokku remote
        run: |
          git remote add dokku dokku@139.59.123.238:todo-list-app || echo "Dokku remote already exists"

      # Step 5: Deploy to Dokku
      - name: Deploy to Dokku
        run: |
          git push dokku main -f  # Push the full history to Dokku
