name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 159.223.72.233 >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy to Dokku
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        eval "$(ssh-agent -s)"
        ssh-add <(echo "${{ secrets.DEPLOY_KEY }}")
        git remote add dokku dokku@159.223.72.233:todo-list-app
        git push dokku main
