name: Node.js CI/CD with Dokku

on:
  push:
    branches:
      - main  # Trigger the pipeline when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Runs after the build job succeeds
    if: github.ref == 'refs/heads/main'  # Only deploy if the push is to the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH for deployment to Dokku server
      - name: Set up SSH key for Dokku
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DOKKU_SERVER_IP }} >> ~/.ssh/known_hosts

      # Deploy to Dokku on DigitalOcean
      - name: Deploy to Dokku
        run: |
          # Add Dokku remote
          git remote add dokku dokku@${{ secrets.DOKKU_SERVER_IP }}:${{ secrets.DOKKU_APP_NAME }}

          # Push the code to Dokku for deployment
          git push dokku main
