name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Dokku
      run: |
        ssh-keyscan -H 159.223.72.233 >> ~/.ssh/known_hosts
        git remote add dokku dokku@159.223.72.233:todo-list-app
        git push dokku main
